# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ddcost < Formula
  desc "A tool that shows a breakdown of Datadog costs in a table."
  homepage "https://github.com/winebarrel/ddcost"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ddcost/releases/download/v1.4.1/ddcost_1.4.1_darwin_amd64.tar.gz"
      sha256 "168931448e7f3bcf0433b98526e0c31e9742b4a342e941a33f7faaca6fda7bab"

      def install
        bin.install 'ddcost'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/ddcost/releases/download/v1.4.1/ddcost_1.4.1_darwin_arm64.tar.gz"
      sha256 "4b2cfaff8141bdd5d39b75df84aa113e8acd3defb326e340e5d2f39b929221e0"

      def install
        bin.install 'ddcost'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/ddcost/releases/download/v1.4.1/ddcost_1.4.1_linux_arm64.tar.gz"
      sha256 "3572a0c6b0e5d0ef585b3a4fb5d484f466ad0b4b63c0fc439fe61d4a602b929f"

      def install
        bin.install 'ddcost'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/ddcost/releases/download/v1.4.1/ddcost_1.4.1_linux_amd64.tar.gz"
      sha256 "84436b2e717eea6f4ed4c1ff99e899967d8a93c746b2c2d5247d084ad6fb3d56"

      def install
        bin.install 'ddcost'
      end
    end
  end
end
